# Generated by Django 3.2.24 on 2024-11-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_table',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
