# Generated by Django 3.2.24 on 2024-11-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0002_alter_hospital_table_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petshop_table',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
