# Generated by Django 3.2.24 on 2024-11-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0003_alter_petshop_table_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_table',
            name='petshop',
        ),
        migrations.AddField(
            model_name='pet_table',
            name='SHOP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petzo_app.petshop_table'),
            preserve_default=False,
        ),
    ]
