# Generated by Django 3.2.24 on 2024-11-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0004_auto_20241122_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('FROMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fromid', to='petzo_app.login_table')),
                ('TOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Toid', to='petzo_app.login_table')),
            ],
        ),
    ]
