# Generated by Django 3.2.24 on 2024-11-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0005_auto_20241123_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccine_request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('request', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petzo_app.user_table')),
                ('VACCINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petzo_app.vaccinedetails_table')),
            ],
        ),
    ]
