# Generated by Django 3.2.24 on 2024-11-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0006_vaccine_request_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petshoprequest_table',
            name='image',
        ),
    ]
