# Generated by Django 3.2.24 on 2024-11-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0008_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_table',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
