# Generated by Django 3.2.24 on 2024-11-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0010_remove_post_table_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('POST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petzo_app.post_table')),
            ],
        ),
    ]
