# Generated by Django 3.2.24 on 2024-11-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0011_comment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_table',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petzo_app.user_table'),
            preserve_default=False,
        ),
    ]
