# Generated by Django 3.2.24 on 2024-11-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0013_user_table_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='image',
        ),
    ]
