# Generated by Django 3.2.24 on 2024-11-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0015_delete_petshop_rating_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_pet_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petzo_app.user_table')),
            ],
        ),
    ]
