# Generated by Django 3.2.24 on 2024-11-27 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petzo_app', '0016_user_pet_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='tips_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('pet_type', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petzo_app.hospital_table')),
            ],
        ),
    ]
